language: java
jdk:
- openjdk8
deploy:
  skip_cleanup: true
  provider: heroku
  strategy: api
  on:
    branch: master
  api_key:
    secure: evtP5pq1/mTGa0Lt2PrHFWLmJAWt2xLCMHfZzOYl/YBqDQyBv4LlnClLqP6UrvBuef8oNURtdkTaNelg5NSwzHe61SFzEKs+Hu3cCnT7PT3PXkwsWRnIyUPAc1BREl3bIIdY1YVvWZcAzVZdDltTQAZFPWRmHS+Z84G9KqnTuaj13eLgl5zwh4Ofk8bz6UoQwf0dpWNV9EQ+rWdNOkyr1H/URGVszwwnhy6V/KwuVqM0DOS8KFrHSe0gqrjg5ajQFcMQnagHU/Ns5igxR/oRxoaHDMoeAsjlFL1iAbcawjnDSVP/7i2thiYWfYPGhMHRunRbNIGPZfvmPL5RmAhI5NaI7LEKx2WCfQA9P4mzEL9P47x+RUqNH/LIhTmIGAtmsqFJTdc8MpJzkVxbgdRKgdNyD4X66K/hp/C1+nxexqak8qNXpNP8A7UxxVQpo+tE9VqLlarzdfmNt6k0n3CwxXCCWsOhp25l/IOqMJyXI7MrsQi6qpgdL3l66QPCfMIQbBYLYYk84vjsJFOGMovtReZtjWNXnZg/l/lw/1XHvawc6+tIDIcT/qk6TMhCcIMJny2rzp6JpP9sGHRrn4LVQTxTN0q4nJnHqU8cbArwwUmZK6H1RXzehRs/yEKBa4sNzp/lJoECXf4IAwzy+Zdieiw0pJYMzIUcmN0kfHfT2rU=
  app: overclock-nc-project
before_install:
- chmod +x mvnw
